ALTER TABLE equipos 
ADD COLUMN IF NOT EXISTS nombre_equipo VARCHAR(150),
ADD COLUMN IF NOT EXISTS ubicacion VARCHAR(150),
ADD COLUMN IF NOT EXISTS ultima_revision VARCHAR(100),
ADD COLUMN IF NOT EXISTS url VARCHAR(255);
